### ISSUE TITLE
of(bitmap)  not working because of this

### ISSUE THREAD

**Issue by BarretWu** [Muddz/QuickShot#17]
private Context getAppContext() {
        if (view == null) {
            throw new NullPointerException("Attempt to save the view failed: view was null");
        }
        return view.getContext().getApplicationContext();
    }
............
            new BitmapSaver(getAppContext(), getBitmap(), saveInternal, path, filename, fileExtension, jpgQuality, listener).execute();

**Comment by Muddz** [comment]
Show me the full code your are using for saving the Bitmap + Library version + minSDK

**Comment by tuinui** [comment]
me too 
my full code is 
![image](https://user-images.githubusercontent.com/7335604/76680486-5dad2580-661b-11ea-8071-dd9f104de2f4.png)

**Comment by Muddz** [comment]
@tuinui 
In your line QuickShot.of(this)` what is `this`? Are you refeering to an actual Bitmap object? 
Also post your error stacktrace

**Comment by DonnieDB** [comment]
QuickShot.of(bitmap).setResultListener(this).save()
minSdkVersion 24. implementation 'com.muddzdev:quickshot:1.1.0'
----------------
save() call BitmapSaver(getAppContext()) and in getAppContext() 
if (view == null) { throw new NullPointerException....
But we did not setup view, only bitmap. Of course it's throws null

**Comment by Muddz** [comment]
@DonnieDB Thanks! I have already fixed and version `1.2.0 `should be up now.

When using Bitmap, you should now pass `Context` as a second parameter.
But only when saving a `Bitmap`.

**Example:**
` QuickShot.of(bitmap, context).setResultListener(this).toJPG().save();`
