### ISSUE TITLE
Path is not useful in api 29-android 10

### ISSUE THREAD

**Issue by mortezaRahimi** [Muddz/QuickShot#19]
@Override
    public void onQuickShotSuccess(String path) {
       File file = new File(path);
       Uri uri = FileProvider.getUriForFile(this, BuildConfig.APPLICATION_ID + 
                                                                    getString(R.string.file_provider_authority), file);
}
Path not working in android 10 in order to get uri and throws exception : 
java.lang.IllegalArgumentException: Failed to find configured root that contains /Pictures/1587840596143.png

**Comment by ahsan-idrees-brainx** [comment]
Same issue

**Comment by RahulSDeshpande** [comment]
@Muddz This library should support `Uri` based image saving & fetching mechanism.
