### ISSUE TITLE
Expose exception data in OnQuickShot failed?

### ISSUE THREAD

**Issue by dasgithub76** [Muddz/QuickShot#20]
Could your proved a reason/exception data in OnQuickShotFailed?  I'd like to be able to send telemetry and help customers if they having a problem.

**Comment by Muddz** [comment]
Hi. Yes this sounds like a good idea. I will look into it

**Comment by Muddz** [comment]
@dasgithub76 Hi. I just released update `1.3.0` which now provides you with a error message in `onQuickShotFailed()`
