### ISSUE TITLE
Save full views (not only visible parts)

### ISSUE THREAD

**Issue by galadril** [Muddz/QuickShot#21]
Question, my page has a lot of data, that doesnt fit your screen.
Is it possible to save the full view, and not only that whats visible in the screen??

Thanks

**Comment by Muddz** [comment]
Try this method:
https://github.com/Muddz/QuickShot/blob/master/quickshot/src/main/java/com/muddzdev/quickshot/QuickShotUtils.java#L29

Copy paste the code in a helper/seperate class and customize it to your use if you target `View `is not a `RecyclerView`.
The `Bitmap `object it returns should to be passed in like `QuickShot.of(bitmap) `

**Comment by galadril** [comment]
Thanks!

I think that your code suggests that all the lists in a row contain the same height??

**Comment by Muddz** [comment]
My quick assumption is that it should work regardless of different heights. Just try it out and see, if its not working, then you should just try to customize the code to fit your case. Much of the work is already done in the method

**Comment by galadril** [comment]
Thanks for everything, awesome plugin

Op za 29 aug. 2020 11:56 schreef Muddi Walid <notifications@github.com>:
