### ISSUE TITLE
couldn't create bitmap of the surfaceview

### ISSUE THREAD

**Issue by SunitRoy2703** [Muddz/QuickShot#24]
I'm trying to capture surface view in camera but it is returning 
couldn't create bitmap of the surfaceview 
on onQuickShotFailed()

it there any reasons?
View current = preview.getSurfaceView(this);
                QuickShot.of(current).setResultListener(this).save();

**Comment by Muddz** [comment]
It should work with SurfaceView since it does in my demo.

This simple way should work:

```
surfaceView = v.findViewById(R.id.surfaceview);
QuickShot.of(surfaceView).setResultListener(this).toPNG().save();
```

I'm not sure what your `preview.getSurfaceView(this);` returns.
Also make sure your SurfaceView is ready and up and running when you call `QuickShot.save()`

**Comment by SunitRoy2703** [comment]
Update I have resolved the issue, it wasn't related to the library 😃
